/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/lending/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List members in the caller's branch scope (FR-MEM-11) */
        get: operations["listMembers"];
        put?: never;
        /** Register a member (FR-MEM-01) */
        post: operations["createMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lending/members/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one member */
        get: operations["getMember"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Running version and git SHA */
        get: operations["version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateMemberRequest: {
            alt_phone?: string;
            /** Format: uuid */
            branch_id: string;
            /** @description Defaults to the tenant currency */
            currency?: string;
            /** Format: date */
            date_of_birth?: string;
            district?: string;
            first_name?: string;
            full_name: string;
            gender?: string;
            id_type: string;
            last_name?: string;
            location?: string;
            marital_status?: string;
            /** Format: int64 */
            monthly_income_minor?: number;
            /** @description Required when id_type is nin (FR-MEM-03) */
            national_id?: string;
            occupation?: string;
            /** Format: uuid */
            officer_user_id?: string;
            other_id_number?: string;
            other_income_source?: string;
            /** @description Any common Uganda form; stored as E.164 (FR-MEM-02) */
            phone: string;
            sub_county?: string;
            village?: string;
        };
        Member: {
            alt_phone_e164?: string;
            /** Format: uuid */
            branch_id?: string;
            /** Format: date-time */
            created_at?: string;
            currency?: string;
            /** Format: date */
            date_of_birth?: string;
            district?: string;
            first_name?: string;
            full_name?: string;
            gender?: string;
            /** Format: uuid */
            id?: string;
            id_type?: string;
            is_blacklisted?: boolean;
            kyc_status?: string;
            last_name?: string;
            location?: string;
            marital_status?: string;
            member_no?: string;
            /** Format: int64 */
            monthly_income_minor?: number;
            national_id?: string;
            occupation?: string;
            /** Format: uuid */
            officer_user_id?: string;
            other_id_number?: string;
            other_income_source?: string;
            phone_e164?: string;
            source?: string;
            status?: string;
            sub_county?: string;
            /** Format: date-time */
            updated_at?: string;
            /** Format: int32 */
            version?: number;
            village?: string;
        };
        MemberListItem: {
            /** Format: uuid */
            branch_id?: string;
            full_name?: string;
            /** Format: uuid */
            id?: string;
            is_blacklisted?: boolean;
            kyc_status?: string;
            member_no?: string;
            national_id_masked?: string;
            phone_e164_masked?: string;
            status?: string;
        };
        MemberPage: {
            items?: components["schemas"]["MemberListItem"][];
            next_cursor?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listMembers: {
        parameters: {
            query?: {
                branch_id?: string[];
                status?: string[];
                q?: string;
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberPage"];
                };
            };
        };
    };
    createMember: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMemberRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
        };
    };
    getMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
        };
    };
    version: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
